# ---------------------------------------------------------------------------
# APP_SECRET (Symfony) generated by Terraform, read by ECS from Secrets Manager
# ---------------------------------------------------------------------------
resource "random_password" "app_secret" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "app_secret" {
  name = "${var.project}-app-secret"

  # Learning env with frequent destroy/apply: without this the name stays
  # reserved for 30 days after destroy and the next apply fails.
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "app_secret" {
  secret_id     = aws_secretsmanager_secret.app_secret.id
  secret_string = random_password.app_secret.result
}

# Lets the ECS execution role read the DB password and APP_SECRET at task start.
# (Delete any older "execution_secrets" copy from other files.)
data "aws_iam_policy_document" "execution_secrets" {
  statement {
    actions = ["secretsmanager:GetSecretValue"]
    resources = [
      aws_db_instance.main.master_user_secret[0].secret_arn,
      aws_secretsmanager_secret.app_secret.arn
    ]
  }
}

resource "aws_iam_role_policy" "execution_secrets" {
  name   = "${var.project}-execution-secrets"
  role   = aws_iam_role.ecs_execution_role.id
  policy = data.aws_iam_policy_document.execution_secrets.json
}
