parameters:
  authors_photo_directory: '%kernel.project_dir%/public/uploads/authors'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

